name: Build QuickJS (Windows x64)

on:
  workflow_dispatch:

jobs:
  build_windows:
    name: Windows x64 Build
    runs-on: windows-latest
    steps:
      - name: Clone QuickJS Repository
        run: git clone https://github.com/bellard/quickjs.git

      - name: Create Output Directory
        run: mkdir qjs\Lib\Win64

      - name: Build QuickJS Static Library using MSVC
        shell: cmd
        run: |
          cd quickjs
          rem Set up MSVC environment; adjust the path if using a different Visual Studio edition
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          rem Compile all .c files in release mode
          cl /c /O2 *.c
          rem Create a static library (.lib) from the object files
          lib /OUT:..\qjs\Lib\Win64\libquickjs.lib *.obj

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: qjs_bin
          path: qjs
