name: Build QuickJS (Windows x64)

on:
  workflow_dispatch:

jobs:
  build_windows:
    name: Windows x64 Build
    runs-on: windows-latest
    steps:
      - name: Clone QuickJS Repository
        run: git clone https://github.com/bellard/quickjs.git

      - name: Setup MSYS2 Environment
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: 'cmake mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-dlfcn'

      - name: Create Make Shim for MSYS2
        shell: msys2 {0}
        run: |
          echo "#! /bin/sh" > /mingw64/bin/make
          echo "\"mingw32-make\" \"\$@\"" >> /mingw64/bin/make

      - name: Build QuickJS Static Library
        shell: msys2 {0}
        run: |
          cd quickjs
          make libquickjs.a

      - name: Prepare Artifact
        shell: bash
        run: |
          cd quickjs
          mkdir -p ../qjs/Lib/Win64
          cp libquickjs.a ../qjs/Lib/Win64/libquickjs.a

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: qjs_bin
          path: qjs
